### ISSUE TITLE
[4️⃣ ] Add router implementation

### ISSUE THREAD

**Issue by natesheridan** [natesheridan/rancid-tomatillos#19]
Add implementation of react-router 

URL endpoints V
![Screen Shot 2021-10-19 at 6 12 06 PM](https://user-images.githubusercontent.com/83609521/138007080-618121b4-ac8f-42df-adee-188a35897b59.png)
o

**Comment by elisebeall** [comment]
@natesheridan I love your use of screenshots.  Where are you grabbing the above image from?  Is this from the project spec?
